title: Blog 
author: Konstantinos Chorianopoulos
email: blog@epidro.me 
description: >- # this means to ignore newlines until "baseurl:"
  This is a long-form blog (similar to medium) with posts about
  various topics. You can follow the updates with the RSS feed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  epidrome

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

show_excerpts: true
permalink: /:slug
